# Generated by Django 3.2 on 2021-04-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField()),
                ('timecase', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='album/photo/')),
            ],
        ),
    ]
