# Generated by Django 3.2 on 2021-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdescript', models.TextField()),
                ('description', models.TextField()),
                ('timecase', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='album/skalaminhossain/')),
            ],
        ),
    ]
