# Generated by Django 3.2 on 2021-05-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_personalblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalblog',
            old_name='sdescript',
            new_name='blogtitle',
        ),
    ]
