# Generated by Django 3.2 on 2021-05-06 21:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

