# Generated by Django 3.2 on 2021-05-06 21:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20210507_0315'),
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalblog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
